services:
  - type: web
    name: zibo-gis-backend
    env: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ZIBOGIS.dll
    envVars:
      - key: PG_CONNECTION_STRING
        value: Host=dpg-d7u4n3ugvqtc73c59rqg-a;Database=place_4vya;Username=place_4vya_user;Password=p8xYyrEy9Edaye3STpmcJrrfC9airGHF;Port=5432
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:1000
